# Generated by Django 4.0.3 on 2022-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-rate'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='founder',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Основатель'),
        ),
        migrations.AddField(
            model_name='company',
            name='staff_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во сотрудников'),
        ),
    ]
