# Generated by Django 4.0.3 on 2022-03-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_company_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Малая', 'Малая'), ('Средняя', 'Средняя'), ('Крупная', 'Крупная')], max_length=128, null=True, verbose_name='Тип компании')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.typecompany'),
        ),
    ]
